version: '3.8'

services:
  streamlit:
    image: python:3.11-slim
    container_name: thai-food-app
    working_dir: ../app
    volumes:
      - .:/app
    ports:
      - "80:80"
    command: >
      sh -c "
        pip install streamlit &&
        streamlit run app.py --server.port=80 --server.enableCORS=false --server.headless=true
      "

